[package]
name = "analyze-unsafe"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]

[dependencies]
cargo = "0"
glob = "0"
rustc-serialize = "0"
libc = "0"
lazy_static = "0.1.*"

[[bin]]
name = "analyze"
path = "src/main.rs"

[[bin]]
name = "download"
path = "src/download/main.rs"
