[package]
name = "analyze-unsafe"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]

[dependencies]
cargo = "0"
#getopts = "0"
glob = "0"
rustc-serialize = "0"

[[bin]]
name = "analyze"
path = "src/analyze/main.rs"

[[bin]]
name = "download"
path = "src/download/main.rs"
